### ISSUE TITLE
Multi thread not supported

### ISSUE THREAD

**Issue by sbrunner** [dmvass/sqlalchemy-easy-profile#13]
When we use it in Gunicorn we frequently get: the assertion error:
Profiling session is already began

**Comment by dmvass** [comment]
Hi @sbrunner, thanks for report! Will try to create a patch next weekend.

**Comment by Tomasz-Kluczkowski** [comment]
I can add to that. Using it with Flask as a middleware as per instructions in README.md and also getting 
`Profiling session is already began` intermittently.

Also I would change this string to:
`Profiling session has already began`

**Comment by dmvass** [comment]
@Tomasz-Kluczkowski I think that the problem is that we instantiate profiler in the middleware class init https://github.com/dmvass/sqlalchemy-easy-profile/blob/master/easy_profile/middleware.py#L38 but don't have time to test it right now, so it will be a good contribution If you fix it.

**Comment by Tomasz-Kluczkowski** [comment]
I will have a look into it.

**Comment by dmvass** [comment]
Fix is already on PyPi

**Comment by sbrunner** [comment]
Thanks :-)
