### ISSUE TITLE
Does not work on python 3.8

### ISSUE THREAD

**Issue by gdbianchi** [dmvass/sqlalchemy-easy-profile#16]
Exception raises when trying to use time.clock on profiler.py.

timer.clock was deprecated since Python 3.3 and removed in 3.8.

From Python DOCs:

Deprecated since version 3.3, will be removed in version 3.8: The behaviour of this function depends on the platform: use perf_counter() or process_time() instead, depending on your requirements, to have a well defined behaviour.

**Comment by dmvass** [comment]
This bug relates to the `WINDOWS` platform. Thank you for report @gdbianchi!
