### ISSUE TITLE
No report shown in console in 1.1.1

### ISSUE THREAD

**Issue by Tomasz-Kluczkowski** [dmvass/sqlalchemy-easy-profile#18]
**Describe the bug**

I have updated to 1.1.1 today.
The SQL report no longer shows in console output.

I am using a mac but not sure if it has anything to do with it.
The setup to enable app - wide console logging of SQL statements is the same.

This is the function that is run if env variable SQL_PROFILING = True. The app is simply flask app passed into the function. All of this works fine in 1.0.3 (and worked for last year) and is as per instructions manual. In the newest version nothing is logged to the console.

```python
def add_sql_profiling(app, config_: Config):
    """
    Adds profiling of the SQL queries performed by sqlalchemy with number of duplicates and execution times.
    """
    if config_.SQL_PROFILING:
        try:
            from easy_profile import EasyProfileMiddleware

            app.wsgi_app = EasyProfileMiddleware(app.wsgi_app)
        except ModuleNotFoundError:
            logging.warning(
                'Easy profile not installed, SQL profiling not available. Install using requirements-for-dev.txt'
            )
```

**To Reproduce**
Steps to reproduce the behavior or test case.

pip install sqlalchemy-easy-profile==1.1.1

**Expected behavior**

SQL statements report is logged in the console.

**Additional context**

**Comment by ranihorev** [comment]
It seems like the duration is always negative

**Comment by dmvass** [comment]
Thanks for reportI! The patch is ready and will be released soon after some testing

**Comment by dmvass** [comment]
@Tomasz-Kluczkowski @ranihorev can someone help me and test this #19 on your setup?
